# Generated by Django 2.0 on 2020-02-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageHost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='host',
            field=models.ManyToManyField(related_name='application', to='manageHost.Host'),
        ),
    ]
